### ISSUE TITLE
Uncaught TypeError: t.map is not a function

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-types#27]
```
Uncaught TypeError: t.map is not a function
    at qo (templates.js:53:18)
    at actions.js:53:13
    at thunk-middleware.js:4:11
    at index.js:24:12
    at promise-middleware.js:20:9
    at Object.dispatch (resolvers-cache-middleware.js:51:10)
    at index.js:202:29
    at index.js:85:4
    at Ug (react-dom.js?ver=18:1:207718)
    at Ag (react-dom.js?ver=18:1:209328)
react-dom.js?ver=18:1 
```
The above error occurred in one of your React components:

    at https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=96588d786d072613d4c6:56:3358
    at https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=96588d786d072613d4c6:48:734
    at WithRegistryProvider(Component)
    at qd (https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/components/index.min.js?ver=3426334688a22e73bc0c:1:202446)
    at Yd (https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/components/index.min.js?ver=3426334688a22e73bc0c:1:202572)
    at Jd (https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/components/index.min.js?ver=3426334688a22e73bc0c:1:204255)
    at div
    at x (https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/keyboard-shortcuts/index.min.js?ver=cb5377c7040e7e246fc0:1:3493)
    at qa (https://blocks.wp.a2z/wp-content/plugins/gutenberg/build/edit-post/index.min.js?ver=feeab9feeb4fa9cd8a33:47:2502)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

_Originally posted by @bobbingwide in https://github.com/bobbingwide/bobbingwide/issues/104#issuecomment-1732591771_

**Comment by bobbingwide** [comment]
The problem is associated with the oik-types plugin and CPTs which implement the template argument,
where the CPT has been modified in oik-type's admin interface.

The CPTs which could have been affected were:

- oik-plugins
- block
- oik-pluginversion
- 
The workaround is to delete the overridden CPT entries in oik-types admin ( Types > Types ).

**Comment by bobbingwide** [comment]
This problem first occurred in blocks.wp.a2z then blocks.wp-a2z.org
where a similar change had been made to the definition of the CPTs.

**Comment by bobbingwide** [comment]
It happened again in wp-secrets.co.uk where I removed "Display in blog home page" from post type supports for oik-plugins.

**Comment by bobbingwide** [comment]
The problem was in `bw_update_post_type` which was changing the `template` from an array to an stdObject.
It needs to remain as an array.

While investigating the fix I wrote some code to display an excerpt of the template when editing a CPT.
